### ISSUE TITLE
About AMI dataset result

### ISSUE THREAD

**Issue by leepeiying** [BUTSpeechFIT/diacorrect#1]
Hi,
Thank you for your sharing, it has been very helpful to me.
May I kindly ask if you could provide experiments on the ami dataset?
Similar to the results in your [previous paper](https://arxiv.org/pdf/2211.06750.pdf?fbclid=IwAR1gpzaYw5BjOz3MaW7LAhe0rCo505_ZM89q7OGC9YepFXlxRI9CEl4ioV0).

Thank you.

**Comment by jyhan03** [comment]
Hi, 
Sorry for the late reply. I just got the AMI results. 

For AMI-2spk headset subsets, after correction, the DER would decrease from 34.63% to 18.91%. Here 
we use EEND-EDA to provide initial diarization results and train a DiaCorret model using the development 
data from scratch. 

I hope this helps.

**Comment by leepeiying** [comment]
Thank you for sharing the experimental results.
